### ISSUE TITLE
More resizing break points

### ISSUE THREAD

**Issue by rjhilgefort** [miromannino/miro-windows-manager#11]
I love this plugin, so thank you for that! I often find that I would like to have more break points when I'm resizing a window. I think there are 3 sizes currently. I was wondering if there is a setting I could use to add more sizes or if you could point me to where I could make the update in my own setup?

**Comment by a7hybnj2** [comment]
@rjhilgefort https://github.com/miromannino/miro-windows-manager/blob/master/MiroWindowsManager.spoon/init.lua#L42

**Comment by rjhilgefort** [comment]
@a7hybnj2 Thanks! I see that `local obj={}` is the root object- does that mean that it's only defined local to that file? Do you know if I have a way to override this from my `init.lua`?

**Comment by rjhilgefort** [comment]
Ah, I was able to do what I was looking for by targetting the object name and reassigning sizes like this:

```lua
spoon.MiroWindowsManager.sizes = { 6/5, 4/3, 3/2, 2/1, 3/1, 4/1, 6/1 }
```
