### ISSUE TITLE
Auto-align after resolution / monitor change

### ISSUE THREAD

**Issue by hkroger** [miromannino/miro-windows-manager#12]
This is just an idea: I have different monitors and sometimes use the laptop screen as well. Is there a way with Miro or just Hammerspoon to detect this and reposition window if the monitor (effectively the resolution) changes?

That would absolutely fantastic feature to have :)

**Comment by rjhilgefort** [comment]
MacOS should remember window positions for monitor configurations until you reboot.

**Comment by hkroger** [comment]
Hmm, you might be right but the impression I have is that the windows often change places. I have to keep monitoring the behaviour.

**Comment by rjhilgefort** [comment]
Yeah, so it sounds like you want a layout feature. This spoon doesn’t offer that, but you might be able to find one that does?

**Comment by hkroger** [comment]
I will have a look, thanks!

**Comment by rjhilgefort** [comment]
Let me know if you do- I'd be really interested in that functionality as well.
