### ISSUE TITLE
love this

### ISSUE THREAD

**Issue by zanuka** [miromannino/miro-windows-manager#13]
the only issue I have with miro-windows-manager is the fact that I didn't discover it sooner. just getting into HammerSpoon and love this 🥄 ... so handy, nice work @miromannino !

**Comment by miromannino** [comment]
I know, some SW Devs I know are even having troubles installing HammerSpoon and that's the only reason they are not using it, definitely I will try to simplify installing procedure.

**Comment by zanuka** [comment]
yeah maybe a simple little install script would do the trick... it performs well on my MacBook Air
