### ISSUE TITLE
Multi Screen Support 

### ISSUE THREAD

**Issue by thomascrha** [miromannino/miro-windows-manager#3]
Firstly great plugin for hammerspoon - I've only just made use of this tool recently and currently its the only plugin I'm using. 

Was wondering if you were interested in implementing a multiscreen setup within your plugin, allowing windows to be moved to different screens. I'm happy to give this a go, I've never programmed in lua (I'm a python programmer) - but looking at the source its easy to read and shouldn't be to difficult to implement. What I was thinking is creating a new short-cut for each detected display. So for example in a 3 screen environment you would have 

`hyper + 1` - Move to screen 1 into the centre.
`hyper + 2` - Move to screen 2 into the centre.
`hyper + 3` - Move to screen 3 into the centre.

Rather than edit your `positions.lua` file I'll create something new like `screens.lua` 

I've found some resources and examples which I'm hoping to integrate into your config. EDIT these are actually for switching between spaces not screens - but i would also like to implement this.

1. [https://github.com/Hammerspoon/hammerspoon/issues/235](url)
2. [https://github.com/szymonkaliski/Dotfiles/tree/master/Dotfiles/hammerspoon](url)

for reference im going over the hs.screen API

- [http://www.hammerspoon.org/docs/hs.screen.html](url)

 

Just wanted your thoughts; and if you think its a good idea incorporating this into your config or creating a new plugin that works with yours ?

**Comment by ericslaw** [comment]
I'd like this too, but tend towards hyper+[ and hyper+] to move current window to the 'next' display.

**Comment by thomascrha** [comment]
Yeah I've been really busy - I've begun the implementation but running into issues with Screen Naming - I've got two 21" screens both from the same manufacturer; MacOSX uses the same identiy name string for both - (one is screen (1) - but thats a displaying thing not a reflection of the actual name) 

I've got some free time this weekend; will try to look into it.

**Comment by ericslaw** [comment]
I am using WinWin via my init.lua:
hyper = {"ctrl", "alt", "cmd"}
hs.loadSpoon("WinWin")
hs.hotkey.bind( hyper, "[", "screen L", function() spoon.WinWin:moveToScreen("left"); spoon.WinWin:centerCursor() end )
hs.hotkey.bind( hyper, "]", "screen R", function() spoon.WinWin:moveToScreen("right"); spoon.WinWin:centerCursor() end )

which works pretty well -- now...
when I undock my laptop -- I'd LOVE to have each 'display' move to separate SPACES that represent each display when they are not attached.
I know the apis for this unofficial - but wondering if that would be possible.
I was once at 4 displays, down to 3 (no displaylink until next macos upgrade),
but undocking was/is a nightmare.

**Comment by a7hybnj2** [comment]
hs.window moveOneScreenEast (west, north, south) are native hammerspoon functions. I have them implemented in my init.lua if you want to take a look: https://github.com/a7hybnj2/dotfiles/blob/master/.hammerspoon/init.lua

**Comment by rjhilgefort** [comment]
@a7hybnj2 That works perfectly! Thanks!!

**Comment by thomascrha** [comment]
Thanks for that !
